//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public int id_equipo { get; set; }
        public string equipo1 { get; set; }
        public int id_tipo_equipo { get; set; }
        public Nullable<int> id_marca { get; set; }
        public string foto_equipo { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Tipo_Equipo Tipo_Equipo { get; set; }
    }
}
