//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Equipo
    {
        public int id_tipo_equipo { get; set; }
        public string tipo_equipo1 { get; set; }
        public int id_clasificacion_equipo { get; set; }
        public string medida { get; set; }
        public string foto_catalogo { get; set; }
    }
}
